language: php

php:
  - 7.0
  - 7.1

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --verbose --ignore-platform-reqs"

script:
  - "vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover"

after_script:
  - "wget https://scrutinizer-ci.com/ocular.phar"
  - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"

after_success:
  - if  [ $TRAVIS_PHP_VERSION = '7.0' ] && [ $TRAVIS_BRANCH = 'master' ]; then sh generate-api.sh; fi

env:
  global:
    secure: XTzPUKON+QTpUnWAlQJWzarcuOVOUZRHnDkvp8wKQp55k/Qsz7tw7edfjwzefGuzqBm1lINR4zpsm9n7zwy4rh97hPh+hFEMT5ozOS4R042YfVv7Xkz2mhGRsyIBwW2xDbFev1z7PekdzAxD8G8Fp0xlVKJzqyX8KqAm4XtubpnHisvItXyiE7qgxPmsQf3UbWr5FPtOBrUz7jHLsGrFM0Z55cYhGsnBTFf+qyo7qbLSUSj6kQUDneiRXzTIAn3xiqpBvHbJ10ByUXcLFycxa1b/FKKSqqBUCoM04l2+gA4g1yFwvsaOcdAsOrJp664nCLgBEGPR4BpEzIuqfOwsiqZEYD1AciIHqFTs42QumTwqGjQIvgt1GfO47/GjmlxvWqeOFB3SMFwT/nna7yS6tcFMhY1kSQmjctLfR81ciDPMoJFzmGDxlatWwz2tI52R+P0NSw6+pxOu0laS+jz+ARftS6KJ/FfJNDBxX9IRAobvMq3ASygz4XQaQ4mD6BEN5muwdPhq5fDUJW08R5FJ9EjyLxTKLLWDN2ENdTG9UpWjx4cuRd1BLOGphIwG//EHfYhktgCKwlhN6y9kvW/4YiFBpgpqTV77zTAXGBus/2T1oQtHfDc+ESiufbd9r67QgidQwVN2w58N/i/0GXl8kjV8V+cJslLEYryMfvIT9GM=