language: php

php:
  - 5.6
  - 7.0

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --verbose"

script:
  - "vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover"

after_script:
  - "wget https://scrutinizer-ci.com/ocular.phar"
  - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"

after_success:
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ]; then sh generate-api.sh; fi
