name: build

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    test:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.2, 8.1, 8.0, 7.4 ]
                laravel: [ 11.*, 10.*, 9.*, 8.*, 7.*, 6.*]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]
                include:
                    -   laravel: 11.*
                        testbench: 9.*
                    -   laravel: 10.*
                        testbench: 8.*
                    -   laravel: 9.*
                        testbench: 7.*
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*
                    -   php: 8.2
                        unitconfig: phpunit_gt_81.xml
                    -   php: 8.1
                        unitconfig: phpunit_gt_81.xml
                    -   php: 8.0
                        unitconfig: phpunit.xml
                    -   php: 7.4
                        unitconfig: phpunit.xml
                exclude:
                    -   laravel: 6.*
                        php: 8
                    -   laravel: 6.*
                        php: 8.1
                    -   laravel: 6.*
                        php: 8.2
                    -   laravel: 7.*
                        php: 8
                    -   laravel: 7.*
                        php: 8.1
                    -   laravel: 7.*
                        php: 8.2
                    -   laravel: 8.*
                        php: 7.4
                    -   laravel: 9.*
                        php: 7.4
                    -   laravel: 10.*
                        php: 7.4
                    -   laravel: 10.*
                        php: 8.0
                    -   laravel: 11.*
                        php: 7.4
                    -   laravel: 11.*
                        php: 8.0
                    -   laravel: 11.*
                        php: 8.1
        runs-on: ${{ matrix.os }}
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        env:
            extensions: intl, json, mbstring, dom, curl, openssl, mcrypt

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP extensions
                id: cache-env
                uses: shivammathur/cache-extensions@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.extensions }}
                    key: php-extensions-cache-v1

            -   name: Setup PHP  ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.extensions }}
                    tools: composer
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Setup Laravel ${{ matrix.laravel }}
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Run tests
                run: |
                    vendor/bin/phpunit -c ${{ matrix.unitconfig }} --coverage-clover=coverage.clover